// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "REPLACE_AWS_REGION",
  "user_pool_id": "REPLACE_USER_POOL_ID",
  "user_pool_web_client_id": "REPLACE_APP_CLIENT_ID",
  "identity_pool_id": "REPLACE_IDENTITY_POOL_ID",
  "pinpoint_app_id": "REPLACE_PINPOINT_APP_ID",
  "aws_appsync_graphqlEndpoint": "REPLACE_APPSYNC_ENDPOINT",
  "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};   

export default awsmobile;  